/*
 * Copyright (c) 2025, Adam G. Sweeney <agsweeney@gmail.com>
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */

#include "webui_api.h"
#include <string.h>
#include <stdbool.h>
#include <stdlib.h>

const char *webui_get_index_html(void)
{
    return "<!DOCTYPE html>"
           "<html lang=\"en\">"
           "<head>"
           "<meta charset=\"UTF-8\">"
           "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">"
           "<title>Device Configuration</title>"
           "<style>"
           "* { box-sizing: border-box; }"
           "body { padding: 0; margin: 0; background-color: #f5f5f5; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif; }"
           ".navbar { background-color: #212529; padding: 15px 0; margin-bottom: 20px; }"
           ".navbar-nav { display: flex; flex-direction: row; list-style: none; margin: 0; padding: 0 20px; justify-content: flex-start; align-items: center; width: 100%; }"
           ".navbar-nav li { margin: 0 15px; }"
           ".navbar-nav a { color: #ffffff; text-decoration: none; font-weight: 500; padding: 8px 16px; border-radius: 4px; transition: background-color 0.2s; }"
           ".navbar-nav a:hover { background-color: rgba(255, 255, 255, 0.1); }"
           ".navbar-nav a.active { background-color: #007bff; }"
           ".content-wrapper { padding: 20px; }"
           ".container { max-width: 800px; background: white; padding: 0; border-radius: 10px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); margin: 0 auto; overflow: hidden; }"
           ".page-header { background-color: #f8f9fa; padding: 20px 30px; border-bottom: 1px solid #dee2e6; }"
           ".page-header h1 { margin: 0; color: #212529; font-size: 1.75rem; font-weight: 700; text-transform: uppercase; }"
           ".page-content { padding: 30px; }"
           ".form-group { margin-bottom: 20px; }"
           "label { font-weight: 600; color: #555; display: block; margin-bottom: 5px; }"
           ".form-control { display: block; width: 100%; padding: 8px 12px; font-size: 14px; line-height: 1.5; color: #495057; background-color: #fff; border: 1px solid #ced4da; border-radius: 4px; }"
           ".form-control:focus { border-color: #80bdff; outline: 0; box-shadow: 0 0 0 0.2rem rgba(0,123,255,0.25); }"
           ".btn { display: inline-block; padding: 8px 16px; font-size: 14px; font-weight: 400; text-align: center; cursor: pointer; border: 1px solid transparent; border-radius: 4px; text-decoration: none; }"
           ".btn-primary { color: #fff; background-color: #007bff; border-color: #007bff; }"
           ".btn-primary:hover { background-color: #0069d9; border-color: #0062cc; }"
           ".alert { position: relative; padding: 12px 20px; margin-bottom: 20px; border: 1px solid transparent; border-radius: 4px; }"
           ".alert-success { color: #155724; background-color: #d4edda; border-color: #c3e6cb; }"
           ".alert-danger { color: #721c24; background-color: #f8d7da; border-color: #f5c6cb; }"
           ".alert-info { color: #0c5460; background-color: #d1ecf1; border-color: #bee5eb; }"
           ".status-card { border: 1px solid #ddd; border-radius: 8px; padding: 0; margin-bottom: 20px; background-color: #fff; overflow: hidden; }"
           ".card-header { background-color: #f8f9fa; padding: 15px 20px; border-bottom: 1px solid #dee2e6; margin: 0; }"
           ".card-header h2 { margin: 0; color: #212529; font-size: 1.25rem; font-weight: 600; }"
           ".card-body { padding: 20px; }"
           "input[type=\"checkbox\"] { width: 18px; height: 18px; margin-right: 8px; vertical-align: middle; }"
           "</style>"
           "</head>"
           "<body>"
           "<nav class=\"navbar\">"
           "<ul class=\"navbar-nav\">"
           "<li><a href=\"/\" class=\"active\">Device Configuration</a></li>"
           "<li><a href=\"/ota\">Firmware Update</a></li>"
           "</ul>"
           "</nav>"
           "<div class=\"content-wrapper\">"
           "<div class=\"container\">"
           "<div class=\"page-header\">"
           "<h1>Device Configuration</h1>"
           "</div>"
           "<div class=\"page-content\">"
           "<div id=\"message\" class=\"alert\" style=\"display: none;\"></div>"
           
           "<!-- Network Configuration -->"
           "<div class=\"status-card\">"
           "<div class=\"card-header\">"
           "<h2>Network Configuration</h2>"
           "</div>"
           "<div class=\"card-body\">"
           "<form id=\"ipConfigForm\">"
           "<div class=\"form-group\">"
           "<label>"
           "<input type=\"checkbox\" id=\"use_dhcp\" onchange=\"toggleStaticFields()\">"
           "<span>Use DHCP (Automatic IP Assignment)</span>"
           "</label>"
           "</div>"
           "<div id=\"staticIpFields\" style=\"display: none;\">"
           "<div class=\"form-group\">"
           "<label for=\"ip_address\">IP Address:</label>"
           "<input type=\"text\" id=\"ip_address\" class=\"form-control\" placeholder=\"192.168.1.100\">"
           "</div>"
           "<div class=\"form-group\">"
           "<label for=\"netmask\">Netmask:</label>"
           "<input type=\"text\" id=\"netmask\" class=\"form-control\" placeholder=\"255.255.255.0\">"
           "</div>"
           "<div class=\"form-group\">"
           "<label for=\"gateway\">Gateway:</label>"
           "<input type=\"text\" id=\"gateway\" class=\"form-control\" placeholder=\"192.168.1.1\">"
           "</div>"
           "</div>"
           "<div id=\"dnsFields\" style=\"display: none;\">"
           "<div class=\"form-group\">"
           "<label for=\"dns1\">Primary DNS:</label>"
           "<input type=\"text\" id=\"dns1\" class=\"form-control\" placeholder=\"8.8.8.8\">"
           "</div>"
           "<div class=\"form-group\">"
           "<label for=\"dns2\">Secondary DNS:</label>"
           "<input type=\"text\" id=\"dns2\" class=\"form-control\" placeholder=\"8.8.4.4\">"
           "</div>"
           "</div>"
           "<button type=\"button\" class=\"btn btn-primary\" onclick=\"saveIpConfig()\">Save Network Configuration</button>"
           "</form>"
           "</div>"
           "</div>"
           
           "<!-- I2C Configuration -->"
           "<div class=\"status-card\">"
           "<div class=\"card-header\">"
           "<h2>I2C Configuration</h2>"
           "</div>"
           "<div class=\"card-body\">"
           "<form id=\"i2cConfigForm\">"
           "<div class=\"form-group\">"
           "<label>"
           "<input type=\"checkbox\" id=\"i2c_pullup_enabled\">"
           "<span>Enable Internal Pull-ups (~45kΩ)</span>"
           "</label>"
           "<p style=\"margin-top: 10px; color: #666; font-size: 14px;\">Disable if using external pull-up resistors. Restart required for changes.</p>"
           "</div>"
           "<button type=\"button\" class=\"btn btn-primary\" onclick=\"saveI2cConfig()\">Save I2C Configuration</button>"
           "</form>"
           "</div>"
           "</div>"
           
           "<!-- MPU6050 Configuration -->"
           "<div class=\"status-card\">"
           "<div class=\"card-header\">"
           "<h2>MPU6050 IMU Configuration</h2>"
           "</div>"
           "<div class=\"card-body\">"
           "<form id=\"mpu6050ConfigForm\">"
           "<div class=\"form-group\">"
           "<label>"
           "<input type=\"checkbox\" id=\"mpu6050_enabled\">"
           "<span>Enable MPU6050</span>"
           "</label>"
           "<p style=\"margin-top: 10px; color: #666; font-size: 14px;\">6-axis IMU (accelerometer + gyroscope + temperature). Data written to Input Assembly 100.</p>"
           "<div style=\"margin-top: 15px;\">"
           "<label for=\"mpu6050_byte_offset\" style=\"display: block; margin-bottom: 5px; font-weight: 600; color: #555;\">Byte Offset:</label>"
           "<select id=\"mpu6050_byte_offset\" class=\"form-control\" style=\"max-width: 200px;\">"
           "<option value=\"0\">0</option>"
           "<option value=\"1\">1</option>"
           "<option value=\"2\">2</option>"
           "<option value=\"3\">3</option>"
           "<option value=\"4\">4</option>"
           "<option value=\"5\">5</option>"
           "<option value=\"6\">6</option>"
           "<option value=\"7\">7</option>"
           "<option value=\"8\">8</option>"
           "<option value=\"9\">9</option>"
           "<option value=\"10\">10</option>"
           "<option value=\"11\">11</option>"
           "<option value=\"12\">12</option>"
           "</select>"
           "<p style=\"margin-top: 5px; color: #666; font-size: 12px;\">MPU6050 uses 20 bytes. Valid range: 0-12.</p>"
           "</div>"
           "<div style=\"margin-top: 15px;\">"
           "<label for=\"tool_weight\" style=\"display: block; margin-bottom: 5px; font-weight: 600; color: #555;\">Tool Weight (lbs):</label>"
           "<input type=\"number\" id=\"tool_weight\" class=\"form-control\" min=\"1\" max=\"255\" step=\"1\" style=\"max-width: 200px;\" readonly>"
           "<p style=\"margin-top: 5px; color: #666; font-size: 12px;\">Controlled by Output Assembly 150 byte 30. Set via EtherNet/IP or Modbus TCP.</p>"
           "</div>"
           "<div style=\"margin-top: 15px;\">"
           "<label for=\"tip_force\" style=\"display: block; margin-bottom: 5px; font-weight: 600; color: #555;\">Tip Force (lbs):</label>"
           "<input type=\"number\" id=\"tip_force\" class=\"form-control\" min=\"1\" max=\"255\" step=\"1\" style=\"max-width: 200px;\" readonly>"
           "<p style=\"margin-top: 5px; color: #666; font-size: 12px;\">Controlled by Output Assembly 150 byte 31. Set via EtherNet/IP or Modbus TCP.</p>"
           "</div>"
           "<div style=\"margin-top: 15px;\">"
           "<label for=\"cylinder_bore\" style=\"display: block; margin-bottom: 5px; font-weight: 600; color: #555;\">Cylinder Bore (inches):</label>"
           "<input type=\"number\" id=\"cylinder_bore\" class=\"form-control\" min=\"0.1\" max=\"10.0\" step=\"0.01\" style=\"max-width: 200px;\">"
           "<p style=\"margin-top: 5px; color: #666; font-size: 12px;\">Cylinder bore diameter in inches (0.1-10.0). Used for pressure calculations.</p>"
           "</div>"
           "</div>"
           "<div style=\"display: flex; gap: 10px; margin-top: 20px;\">"
           "<a href=\"/mpu6050status\" class=\"btn btn-primary\">MPU6050 Status</a>"
           "<div style=\"display: flex; gap: 10px; margin-top: 10px;\">"
           "<button type=\"button\" class=\"btn btn-primary\" onclick=\"saveMpu6050Config()\">Save MPU6050 Configuration</button>"
           "</div>"
           "</div>"
           "</form>"
           "</div>"
           "</div>"
           
           "<!-- Reboot Button -->"
           "<div class=\"status-card\">"
           "<div class=\"card-header\">"
           "<h2>System</h2>"
           "</div>"
           "<div class=\"card-body\">"
           "<button type=\"button\" class=\"btn btn-primary\" onclick=\"rebootDevice()\">Reboot Device</button>"
           "</div>"
           "</div>"
           
           "</div>"
           "<footer style=\"text-align: center; padding: 20px 30px; border-top: 1px solid #dee2e6; color: #666; background-color: #f8f9fa;\">OpENer Ethernet/IP for ESP32-P4 | Adam G Sweeney 11-15-2025</footer>"
           "</div>"
           "</div>"
           "<script>"
           "function showMessage(text, type) {"
           "  const msg = document.getElementById('message');"
           "  if (msg) {"
           "    msg.textContent = text;"
           "    msg.className = 'alert alert-' + type;"
           "    msg.style.display = 'block';"
           "    setTimeout(function() { msg.style.display = 'none'; }, 5000);"
           "  } else {"
           "    console.log('[' + type.toUpperCase() + '] ' + text);"
           "  }"
           "}"
           "function loadIpConfig() {"
           "  fetch('/api/ipconfig')"
           "    .then(r => {"
           "      if (!r.ok) throw new Error('HTTP ' + r.status);"
           "      return r.json();"
           "    })"
           "    .then(data => {"
           "      const dhcpCheckbox = document.getElementById('use_dhcp');"
           "      const staticFields = document.getElementById('staticIpFields');"
           "      const dnsFields = document.getElementById('dnsFields');"
           "      if (dhcpCheckbox && data.use_dhcp !== undefined) {"
           "        dhcpCheckbox.checked = data.use_dhcp;"
           "        toggleStaticFields();"
           "      }"
           "      const ipAddr = document.getElementById('ip_address');"
           "      const netmask = document.getElementById('netmask');"
           "      const gateway = document.getElementById('gateway');"
           "      const dns1 = document.getElementById('dns1');"
           "      const dns2 = document.getElementById('dns2');"
           "      if (ipAddr) ipAddr.value = (data.ip_address && data.ip_address !== '0.0.0.0') ? data.ip_address : '';"
           "      if (netmask) netmask.value = (data.netmask && data.netmask !== '0.0.0.0') ? data.netmask : '';"
           "      if (gateway) gateway.value = (data.gateway && data.gateway !== '0.0.0.0') ? data.gateway : '';"
           "      if (dns1) dns1.value = (data.dns1 && data.dns1 !== '0.0.0.0') ? data.dns1 : '';"
           "      if (dns2) dns2.value = (data.dns2 && data.dns2 !== '0.0.0.0') ? data.dns2 : '';"
           "    })"
           "    .catch(err => {"
           "      console.error('Failed to load IP configuration:', err);"
           "    });"
           "}"
           "function toggleStaticFields() {"
           "  const dhcpCheckbox = document.getElementById('use_dhcp');"
           "  const staticFields = document.getElementById('staticIpFields');"
           "  const dnsFields = document.getElementById('dnsFields');"
           "  if (dhcpCheckbox && staticFields && dnsFields) {"
           "    const useDhcp = dhcpCheckbox.checked;"
           "    staticFields.style.display = useDhcp ? 'none' : 'block';"
           "    dnsFields.style.display = useDhcp ? 'none' : 'block';"
           "  }"
           "}"
           "function saveIpConfig() {"
           "  const data = {"
           "    use_dhcp: document.getElementById('use_dhcp').checked,"
           "    ip_address: document.getElementById('ip_address').value,"
           "    netmask: document.getElementById('netmask').value,"
           "    gateway: document.getElementById('gateway').value,"
           "    dns1: document.getElementById('dns1').value,"
           "    dns2: document.getElementById('dns2').value"
           "  };"
           "  fetch('/api/ipconfig', {"
           "    method: 'POST',"
           "    headers: { 'Content-Type': 'application/json' },"
           "    body: JSON.stringify(data)"
           "  })"
           "    .then(r => {"
           "      if (!r.ok) throw new Error('HTTP ' + r.status);"
           "      return r.json();"
           "    })"
           "    .then(data => {"
           "      if (data.status === 'ok') {"
           "        showMessage(data.message, 'success');"
           "      } else {"
           "        showMessage('Failed to save IP configuration', 'danger');"
           "      }"
           "    })"
           "    .catch(err => {"
           "      console.error('Failed to save IP configuration:', err);"
           "      showMessage('Failed to save IP configuration', 'danger');"
           "    });"
           "}"
           "function loadI2cConfig() {"
           "  fetch('/api/i2c/pullup')"
           "    .then(r => {"
           "      if (!r.ok) throw new Error('HTTP ' + r.status);"
           "      return r.json();"
           "    })"
           "    .then(data => {"
           "      const i2cCheckbox = document.getElementById('i2c_pullup_enabled');"
           "      if (i2cCheckbox && data.enabled !== undefined) {"
           "        i2cCheckbox.checked = data.enabled;"
           "      }"
           "    })"
           "    .catch(err => {"
           "      console.error('Failed to load I2C configuration:', err);"
           "    });"
           "}"
           "function saveI2cConfig() {"
           "  const data = {"
           "    enabled: document.getElementById('i2c_pullup_enabled').checked"
           "  };"
           "  fetch('/api/i2c/pullup', {"
           "    method: 'POST',"
           "    headers: { 'Content-Type': 'application/json' },"
           "    body: JSON.stringify(data)"
           "  })"
           "    .then(r => {"
           "      if (!r.ok) throw new Error('HTTP ' + r.status);"
           "      return r.json();"
           "    })"
           "    .then(data => {"
           "      if (data.status === 'ok') {"
           "        showMessage('I2C configuration saved successfully', 'success');"
           "      } else {"
           "        showMessage('Failed to save I2C configuration', 'danger');"
           "      }"
           "    })"
           "    .catch(err => {"
           "      console.error('Failed to save I2C configuration:', err);"
           "      showMessage('Failed to save I2C configuration', 'danger');"
           "    });"
           "}"
           "function loadMpu6050Config() {"
           "  fetch('/api/mpu6050/enabled')"
           "    .then(r => {"
           "      if (!r.ok) throw new Error('HTTP ' + r.status);"
           "      return r.json();"
           "    })"
           "    .then(data => {"
           "      const mpu6050Enabled = document.getElementById('mpu6050_enabled');"
           "      if (mpu6050Enabled && data.enabled !== undefined) {"
           "        mpu6050Enabled.checked = data.enabled;"
           "      }"
           "    })"
           "    .catch(err => {"
           "      console.error('Failed to load MPU6050 enabled state:', err);"
           "    });"
           "  fetch('/api/mpu6050/byteoffset')"
           "    .then(r => {"
           "      if (!r.ok) throw new Error('HTTP ' + r.status);"
           "      return r.json();"
           "    })"
           "    .then(data => {"
           "      const byteOffsetSelect = document.getElementById('mpu6050_byte_offset');"
           "      if (byteOffsetSelect && data.start_byte !== undefined) {"
           "        byteOffsetSelect.value = data.start_byte;"
           "      }"
           "    })"
           "    .catch(err => {"
           "      console.error('Failed to load MPU6050 byte offset:', err);"
           "    });"
           "  fetch('/api/status')"
           "    .then(r => {"
           "      if (!r.ok) throw new Error('HTTP ' + r.status);"
           "      return r.json();"
           "    })"
           "    .then(data => {"
           "      if (data.output_assembly_150 && data.output_assembly_150.raw_bytes) {"
           "        const bytes = data.output_assembly_150.raw_bytes;"
           "        const toolWeightInput = document.getElementById('tool_weight');"
           "        const tipForceInput = document.getElementById('tip_force');"
           "        if (toolWeightInput && bytes[30] !== undefined) {"
           "          toolWeightInput.value = bytes[30];"
           "        }"
           "        if (tipForceInput && bytes[31] !== undefined) {"
           "          tipForceInput.value = bytes[31];"
           "        }"
           "      }"
           "    })"
           "    .catch(err => {"
           "      console.error('Failed to load tool weight and tip force from output assembly:', err);"
           "    });"
           "  fetch('/api/mpu6050/cylinderbore')"
           "    .then(r => {"
           "      if (!r.ok) throw new Error('HTTP ' + r.status);"
           "      return r.json();"
           "    })"
           "    .then(data => {"
           "      const cylinderBoreInput = document.getElementById('cylinder_bore');"
           "      if (cylinderBoreInput && data.cylinder_bore !== undefined) {"
           "        cylinderBoreInput.value = data.cylinder_bore;"
           "      }"
           "    })"
           "    .catch(err => {"
           "      console.error('Failed to load cylinder bore:', err);"
           "    });"
           "}"
           "function saveMpu6050Config() {"
           "  const enabled = document.getElementById('mpu6050_enabled').checked;"
           "  const byteOffsetSelect = document.getElementById('mpu6050_byte_offset');"
           "  const startByte = byteOffsetSelect ? parseInt(byteOffsetSelect.value, 10) : 0;"
           "  if (isNaN(startByte) || startByte < 0 || startByte > 12) {"
           "    showMessage('Invalid byte offset. Must be between 0 and 12.', 'danger');"
           "    return;"
           "  }"
           "  const cylinderBoreInput = document.getElementById('cylinder_bore');"
           "  const cylinderBore = cylinderBoreInput ? parseFloat(cylinderBoreInput.value) : 1.0;"
           "  if (isNaN(cylinderBore) || cylinderBore <= 0 || cylinderBore > 10.0) {"
           "    showMessage('Invalid cylinder bore. Must be between 0.1 and 10.0 inches.', 'danger');"
           "    return;"
           "  }"
           "  Promise.all(["
           "    fetch('/api/mpu6050/enabled', {"
           "      method: 'POST',"
           "      headers: { 'Content-Type': 'application/json' },"
           "      body: JSON.stringify({ enabled: enabled })"
           "    }),"
           "    fetch('/api/mpu6050/byteoffset', {"
           "      method: 'POST',"
           "      headers: { 'Content-Type': 'application/json' },"
           "      body: JSON.stringify({ start_byte: startByte })"
           "    }),"
           "    fetch('/api/mpu6050/cylinderbore', {"
           "      method: 'POST',"
           "      headers: { 'Content-Type': 'application/json' },"
           "      body: JSON.stringify({ cylinder_bore: cylinderBore })"
           "    })"
           "  ])"
           "    .then(responses => Promise.all(responses.map(r => {"
           "      if (!r.ok) throw new Error('HTTP ' + r.status);"
           "      return r.json();"
           "    })))"
           "    .then(results => {"
           "      if (results[0].status === 'ok' && results[1].status === 'ok' && results[2].status === 'ok') {"
           "        showMessage('MPU6050 configuration saved successfully', 'success');"
           "      } else {"
           "        showMessage('Failed to save MPU6050 configuration', 'danger');"
           "      }"
           "    })"
           "    .catch(err => {"
           "      console.error('Failed to save MPU6050 configuration:', err);"
           "      showMessage('Failed to save MPU6050 configuration', 'danger');"
           "    });"
           "}"
           "function rebootDevice() {"
           "  if (!confirm('Are you sure you want to reboot the device? This will disconnect your current session.')) {"
           "    return;"
           "  }"
           "  fetch('/api/reboot', {"
           "    method: 'POST',"
           "    headers: { 'Content-Type': 'application/json' }"
           "  })"
           "    .then(r => r.json())"
           "    .then(data => {"
           "      showMessage(data.message || 'Device rebooting...', 'info');"
           "      setTimeout(function() { window.location.reload(); }, 2000);"
           "    })"
           "    .catch(err => {"
           "      console.error('Failed to reboot device:', err);"
           "      showMessage('Failed to reboot device', 'danger');"
           "    });"
           "}"
           "window.onload = function() {"
           "  loadIpConfig();"
           "  loadI2cConfig();"
           "  loadMpu6050Config();"
           "};"
           "</script>"
           "</body>"
           "</html>";
}

const char *webui_get_status_html(void)
{
    return "";  // Status page removed
}

const char *webui_get_ethernetip_html(void)
{
    return "";  // Output assembly page removed
}

const char *webui_get_input_assembly_html(void)
{
    return "";  // Input assembly page removed
}

const char *webui_get_mcpconfig_html(void)
{
    return "";  // MCP230x removed from project
}

const char *webui_get_vl53l1xconfig_html(void)
{
    return "";  // VL53L1x removed from project
}

const char *webui_get_mpu6050_html(void)
{
    return "<!DOCTYPE html>"
           "<html lang=\"en\">"
           "<head>"
           "<meta charset=\"UTF-8\">"
           "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">"
           "<title>MPU6050 Configuration</title>"
           "<style>"
           "* { box-sizing: border-box; }"
           "body { padding: 0; margin: 0; background-color: #f5f5f5; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif; }"
           ".navbar { background-color: #212529; padding: 15px 0; margin-bottom: 20px; }"
           ".navbar-nav { display: flex; flex-direction: row; list-style: none; margin: 0; padding: 0 20px; justify-content: flex-start; align-items: center; width: 100%; }"
           ".navbar-nav li { margin: 0 15px; }"
           ".navbar-nav a { color: #ffffff; text-decoration: none; font-weight: 500; padding: 8px 16px; border-radius: 4px; transition: background-color 0.2s; }"
           ".navbar-nav a:hover { background-color: rgba(255, 255, 255, 0.1); }"
           ".navbar-nav a.active { background-color: #007bff; }"
           ".content-wrapper { padding: 20px; }"
           ".container { max-width: 800px; background: white; padding: 0; border-radius: 10px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); margin: 0 auto; overflow: hidden; }"
           ".page-header { background-color: #f8f9fa; padding: 20px 30px; border-bottom: 1px solid #dee2e6; }"
           ".page-header h1 { margin: 0; color: #212529; font-size: 1.75rem; font-weight: 700; text-transform: uppercase; }"
           ".page-content { padding: 30px; }"
           ".form-group { margin-bottom: 20px; }"
           "label { font-weight: 600; color: #555; display: block; margin-bottom: 5px; }"
           ".form-control { display: block; width: 100%; padding: 8px 12px; font-size: 14px; line-height: 1.5; color: #495057; background-color: #fff; border: 1px solid #ced4da; border-radius: 4px; }"
           ".form-control:focus { border-color: #80bdff; outline: 0; box-shadow: 0 0 0 0.2rem rgba(0,123,255,0.25); }"
           ".btn { display: inline-block; padding: 8px 16px; font-size: 14px; font-weight: 400; text-align: center; cursor: pointer; border: 1px solid transparent; border-radius: 4px; text-decoration: none; }"
           ".btn-primary { color: #fff; background-color: #007bff; border-color: #007bff; }"
           ".btn-primary:hover { background-color: #0069d9; border-color: #0062cc; }"
           ".alert { position: relative; padding: 12px 20px; margin-bottom: 20px; border: 1px solid transparent; border-radius: 4px; }"
           ".alert-success { color: #155724; background-color: #d4edda; border-color: #c3e6cb; }"
           ".alert-danger { color: #721c24; background-color: #f8d7da; border-color: #f5c6cb; }"
           ".status-card { border: 1px solid #ddd; border-radius: 8px; padding: 0; margin-bottom: 20px; background-color: #fff; overflow: hidden; }"
           ".card-header { background-color: #f8f9fa; padding: 15px 20px; border-bottom: 1px solid #dee2e6; margin: 0; }"
           ".card-header h2 { margin: 0; color: #212529; font-size: 1.25rem; font-weight: 600; }"
           ".card-body { padding: 20px; }"
           "</style>"
           "</head>"
           "<body>"
           "<nav class=\"navbar\">"
           "<ul class=\"navbar-nav\">"
           "<li><a href=\"/\">Device Configuration</a></li>"
           "<li><a href=\"/ota\">Firmware Update</a></li>"
           "</ul>"
           "</nav>"
           "<div class=\"content-wrapper\">"
           "<div class=\"container\">"
           "<div class=\"page-header\">"
           "<h1>MPU6050 Configuration</h1>"
           "</div>"
           "<div class=\"page-content\">"
           "<div id=\"message\" class=\"alert\" style=\"display: none;\"></div>"
           "<div class=\"status-card\">"
           "<div class=\"card-header\">"
           "<h2>Data Byte Offset</h2>"
           "</div>"
           "<div class=\"card-body\">"
           "<form id=\"mpu6050ByteOffsetForm\">"
           "<div class=\"form-group\">"
           "<label for=\"byte_offset\">Start Byte Offset (0-12):</label>"
           "<input type=\"number\" id=\"byte_offset\" class=\"form-control\" min=\"0\" max=\"12\" step=\"1\">"
           "<p style=\"margin-top: 10px; color: #666; font-size: 14px;\">MPU6050 data uses 20 bytes (5 int32_t values: roll, pitch, ground angle, bottom pressure, top pressure). Valid range: 0-12 (to fit within 32-byte assembly).</p>"
           "</div>"
           "<button type=\"button\" class=\"btn btn-primary\" onclick=\"saveByteOffset()\">Save Byte Offset</button>"
           "</form>"
           "</div>"
           "</div>"
           "</div>"
           "<footer style=\"text-align: center; padding: 20px 30px; border-top: 1px solid #dee2e6; color: #666; background-color: #f8f9fa;\">OpENer Ethernet/IP for ESP32-P4 | Adam G Sweeney 11-15-2025</footer>"
           "</div>"
           "</div>"
           "<script>"
           "function showMessage(text, type) {"
           "  const msg = document.getElementById('message');"
           "  if (msg) {"
           "    msg.textContent = text;"
           "    msg.className = 'alert alert-' + type;"
           "    msg.style.display = 'block';"
           "    setTimeout(function() { msg.style.display = 'none'; }, 5000);"
           "  } else {"
           "    console.log('[' + type.toUpperCase() + '] ' + text);"
           "  }"
           "}"
           "function loadByteOffset() {"
           "  fetch('/api/mpu6050/byteoffset')"
           "    .then(r => {"
           "      if (!r.ok) throw new Error('HTTP ' + r.status);"
           "      return r.json();"
           "    })"
           "    .then(data => {"
           "      const byteOffsetInput = document.getElementById('byte_offset');"
           "      if (byteOffsetInput && data.start_byte !== undefined) {"
           "        byteOffsetInput.value = data.start_byte;"
           "      }"
           "    })"
           "    .catch(err => {"
           "      console.error('Failed to load byte offset:', err);"
           "    });"
           "}"
           "function saveByteOffset() {"
           "  const byteOffsetInput = document.getElementById('byte_offset');"
           "  if (!byteOffsetInput) {"
           "    showMessage('Error: Byte offset input not found', 'danger');"
           "    return;"
           "  }"
           "  const startByte = parseInt(byteOffsetInput.value, 10);"
           "  if (isNaN(startByte) || startByte < 0 || startByte > 12) {"
           "    showMessage('Invalid byte offset. Must be between 0 and 12.', 'danger');"
           "    return;"
           "  }"
           "  fetch('/api/mpu6050/byteoffset', {"
           "    method: 'POST',"
           "    headers: { 'Content-Type': 'application/json' },"
           "    body: JSON.stringify({ start_byte: startByte })"
           "  })"
           "    .then(r => {"
           "      if (!r.ok) throw new Error('HTTP ' + r.status);"
           "      return r.json();"
           "    })"
           "    .then(data => {"
           "      if (data.status === 'ok') {"
           "        showMessage('Byte offset saved successfully', 'success');"
           "      } else {"
           "        showMessage('Failed to save byte offset', 'danger');"
           "      }"
           "    })"
           "    .catch(err => {"
           "      console.error('Failed to save byte offset:', err);"
           "      showMessage('Failed to save byte offset', 'danger');"
           "    });"
           "}"
           "window.onload = function() {"
           "  loadByteOffset();"
           "};"
           "</script>"
           "</body>"
           "</html>";
}

const char *webui_get_ota_html(void)
{
    return "<!DOCTYPE html>"
           "<html lang=\"en\">"
           "<head>"
           "<meta charset=\"UTF-8\">"
           "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">"
           "<title>Firmware Update</title>"
           "<style>"
           "* { box-sizing: border-box; }"
           "body { padding: 0; margin: 0; background-color: #f5f5f5; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif; }"
           ".navbar { background-color: #212529; padding: 15px 0; margin-bottom: 20px; }"
           ".navbar-nav { display: flex; flex-direction: row; list-style: none; margin: 0; padding: 0 20px; justify-content: flex-start; align-items: center; width: 100%; }"
           ".navbar-nav li { margin: 0 15px; }"
           ".navbar-nav a { color: #ffffff; text-decoration: none; font-weight: 500; padding: 8px 16px; border-radius: 4px; transition: background-color 0.2s; }"
           ".navbar-nav a:hover { background-color: rgba(255, 255, 255, 0.1); }"
           ".navbar-nav a.active { background-color: #007bff; }"
           ".content-wrapper { padding: 20px; }"
           ".container { max-width: 800px; background: white; padding: 0; border-radius: 10px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); margin: 0 auto; overflow: hidden; }"
           ".page-header { background-color: #f8f9fa; padding: 20px 30px; border-bottom: 1px solid #dee2e6; }"
           ".page-header h1 { margin: 0; color: #212529; font-size: 1.75rem; font-weight: 700; text-transform: uppercase; }"
           ".page-content { padding: 30px; }"
           ".form-group { margin-bottom: 20px; }"
           "label { font-weight: 600; color: #555; display: block; margin-bottom: 5px; }"
           ".form-control { display: block; width: 100%; padding: 8px 12px; font-size: 14px; line-height: 1.5; color: #495057; background-color: #fff; border: 1px solid #ced4da; border-radius: 4px; }"
           ".form-control:focus { border-color: #80bdff; outline: 0; box-shadow: 0 0 0 0.2rem rgba(0,123,255,0.25); }"
           "input[type=\"file\"] { display: block; width: 100%; padding: 8px 12px; font-size: 14px; line-height: 1.5; color: #495057; background-color: #fff; border: 1px solid #ced4da; border-radius: 4px; cursor: pointer; }"
           "input[type=\"file\"]::-webkit-file-upload-button { padding: 6px 12px; margin-right: 12px; color: #fff; background-color: #007bff; border: 1px solid #007bff; border-radius: 4px; cursor: pointer; font-size: 14px; font-weight: 400; }"
           "input[type=\"file\"]::-webkit-file-upload-button:hover { background-color: #0069d9; border-color: #0062cc; }"
           "input[type=\"file\"]::file-selector-button { padding: 6px 12px; margin-right: 12px; color: #fff; background-color: #007bff; border: 1px solid #007bff; border-radius: 4px; cursor: pointer; font-size: 14px; font-weight: 400; }"
           "input[type=\"file\"]::file-selector-button:hover { background-color: #0069d9; border-color: #0062cc; }"
           ".btn { display: inline-block; padding: 8px 16px; font-size: 14px; font-weight: 400; text-align: center; cursor: pointer; border: 1px solid transparent; border-radius: 4px; text-decoration: none; }"
           ".btn-primary { color: #fff; background-color: #007bff; border-color: #007bff; }"
           ".btn-primary:hover { background-color: #0069d9; border-color: #0062cc; }"
           ".alert { position: relative; padding: 12px 20px; margin-bottom: 20px; border: 1px solid transparent; border-radius: 4px; }"
           ".alert-success { color: #155724; background-color: #d4edda; border-color: #c3e6cb; }"
           ".alert-danger { color: #721c24; background-color: #f8d7da; border-color: #f5c6cb; }"
           ".alert-warning { color: #856404; background-color: #fff3cd; border-color: #ffeaa7; }"
           ".alert-info { color: #0c5460; background-color: #d1ecf1; border-color: #bee5eb; }"
           "</style>"
           "</head>"
           "<body>"
           "<nav class=\"navbar\">"
           "<ul class=\"navbar-nav\">"
           "<li><a href=\"/\">Device Configuration</a></li>"
           "<li><a href=\"/ota\" class=\"active\">Firmware Update</a></li>"
           "</ul>"
           "</nav>"
           "<div class=\"content-wrapper\">"
           "<div class=\"container\">"
           "<div class=\"page-header\">"
           "<h1>Firmware Update</h1>"
           "</div>"
           "<div class=\"page-content\">"
           "<div style=\"margin-bottom: 20px; padding: 12px; background-color: #f8f9fa; border-left: 4px solid #007bff; border-radius: 4px;\">"
           "<p style=\"margin: 0; color: #495057; font-size: 14px; line-height: 1.6;\">"
           "<strong>Over-The-Air (OTA) Firmware Update:</strong> Upload a new firmware binary file (.bin) to update the device firmware wirelessly. "
           "Select the firmware file and click \"Start Update\" to begin the process. The device will automatically reboot after a successful update. "
           "Ensure the firmware file is compatible with your device model and that you maintain a stable network connection during the update process."
           "</p>"
           "</div>"
           "<div id=\"message\" class=\"alert\" style=\"display: none;\"></div>"
           "<form id=\"otaForm\">"
           "<div class=\"form-group\">"
           "<label for=\"firmware_file\">Firmware File (.bin):</label>"
           "<input type=\"file\" id=\"firmware_file\" class=\"form-control\" accept=\".bin\">"
           "</div>"
           "<button type=\"button\" class=\"btn btn-primary\" onclick=\"startOTA()\" style=\"margin-top:20px;\">Start Update</button>"
           "</form>"
           "</div>"
           "<footer style=\"text-align: center; padding: 20px 30px; border-top: 1px solid #dee2e6; color: #666; background-color: #f8f9fa;\">OpENer Ethernet/IP for ESP32-P4 | Adam G Sweeney 11-15-2025</footer>"
           "</div>"
           "</div>"
           "<script>"
           "function showMessage(text, type) {"
           "  const msg = document.getElementById('message');"
           "  if (msg) {"
           "    msg.textContent = text;"
           "    msg.className = 'alert alert-' + type;"
           "    msg.style.display = 'block';"
           "  } else {"
           "    console.log('[' + type.toUpperCase() + '] ' + text);"
           "  }"
           "}"
           "function startOTA() {"
           "  const fileInput = document.getElementById('firmware_file');"
           "  if (!fileInput) {"
           "    showMessage('Error: File input not found', 'danger');"
           "    return;"
           "  }"
           "  const file = fileInput.files[0];"
           "  if (!file) {"
           "    showMessage('Please select a firmware file', 'warning');"
           "    return;"
           "  }"
           "  const formData = new FormData();"
           "  formData.append('firmware', file);"
           "  showMessage('Uploading firmware...', 'info');"
           "  fetch('/api/ota/update', {"
           "    method: 'POST',"
           "    body: formData"
           "  })"
           "    .then(function(r) {"
           "      if (!r.ok) {"
           "        throw new Error('HTTP ' + r.status);"
           "      }"
           "      return r.json();"
           "    })"
           "    .then(function(data) {"
           "      if (data.status === 'ok') {"
           "        showMessage('Firmware uploaded successfully. Device will reboot in a few seconds...', 'success');"
           "        setTimeout(function() {"
           "          window.location.href = '/';"
           "        }, 5000);"
           "      } else {"
           "        showMessage('Error: ' + (data.message || 'Unknown error'), 'danger');"
           "      }"
           "    })"
           "    .catch(function(err) {"
           "      showMessage('Error: ' + err.message, 'danger');"
           "    });"
           "}"
           "</script>"
           "</body>"
           "</html>";
}

const char *webui_get_mpu6050_status_html(void)
{
    return "<!DOCTYPE html>"
           "<html lang=\"en\">"
           "<head>"
           "<meta charset=\"UTF-8\">"
           "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">"
           "<title>MPU6050 Status</title>"
           "<style>"
           "* { box-sizing: border-box; }"
           "body { padding: 0; margin: 0; background-color: #f5f5f5; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif; }"
           ".navbar { background-color: #212529; padding: 15px 0; margin-bottom: 20px; }"
           ".navbar-nav { display: flex; flex-direction: row; list-style: none; margin: 0; padding: 0 20px; justify-content: flex-start; align-items: center; width: 100%; }"
           ".navbar-nav li { margin: 0 15px; }"
           ".navbar-nav a { color: #ffffff; text-decoration: none; font-weight: 500; padding: 8px 16px; border-radius: 4px; transition: background-color 0.2s; }"
           ".navbar-nav a:hover { background-color: rgba(255, 255, 255, 0.1); }"
           ".navbar-nav a.active { background-color: #007bff; }"
           ".content-wrapper { padding: 20px; }"
           ".container { max-width: 800px; background: white; padding: 0; border-radius: 10px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); margin: 0 auto; overflow: hidden; }"
           ".page-header { background-color: #f8f9fa; padding: 20px 30px; border-bottom: 1px solid #dee2e6; }"
           ".page-header h1 { margin: 0; color: #212529; font-size: 1.75rem; font-weight: 700; text-transform: uppercase; }"
           ".page-content { padding: 30px; }"
           ".status-card { border: 1px solid #ddd; border-radius: 8px; padding: 0; margin-bottom: 20px; background-color: #fff; overflow: hidden; }"
           ".card-header { background-color: #f8f9fa; padding: 15px 20px; border-bottom: 1px solid #dee2e6; margin: 0; }"
           ".card-header h2 { margin: 0; color: #212529; font-size: 1.25rem; font-weight: 600; }"
           ".card-body { padding: 20px; }"
           ".status-value { font-size: 24px; font-weight: bold; color: #007bff; }"
           ".status-label { font-weight: 600; color: #555; margin-bottom: 5px; }"
           ".status-row { display: flex; justify-content: space-between; align-items: center; margin-bottom: 15px; padding-bottom: 15px; border-bottom: 1px solid #eee; }"
           ".status-row:last-child { border-bottom: none; margin-bottom: 0; padding-bottom: 0; }"
           ".status-info { font-size: 14px; color: #666; margin-top: 5px; }"
           "</style>"
           "</head>"
           "<body>"
           "<nav class=\"navbar\">"
           "<ul class=\"navbar-nav\">"
           "<li><a href=\"/\">Device Configuration</a></li>"
           "<li><a href=\"/mpu6050status\" class=\"active\">MPU6050 Status</a></li>"
           "<li><a href=\"/ota\">Firmware Update</a></li>"
           "</ul>"
           "</nav>"
           "<div class=\"content-wrapper\">"
           "<div class=\"container\">"
           "<div class=\"page-header\">"
           "<h1>MPU6050 Status</h1>"
           "</div>"
           "<div class=\"page-content\">"
           "<div style=\"margin-bottom: 20px; padding: 12px; background-color: #f8f9fa; border-left: 4px solid #007bff; border-radius: 4px;\">"
           "<p style=\"margin: 0; color: #495057; font-size: 14px; line-height: 1.6;\">"
           "<strong>Real-Time Sensor Data:</strong> This page displays live orientation and pressure data from the MPU6050 IMU sensor. "
           "Data updates automatically every 250ms."
           "</p>"
           "</div>"
           
           "<!-- Orientation Data -->"
           "<div class=\"status-card\">"
           "<div class=\"card-header\">"
           "<h2>Orientation</h2>"
           "</div>"
           "<div class=\"card-body\">"
           "<div class=\"status-row\">"
           "<div>"
           "<div class=\"status-label\">Roll</div>"
           "<div class=\"status-value\" id=\"roll\">-</div>"
           "<div class=\"status-info\" id=\"roll_scaled\"></div>"
           "</div>"
           "</div>"
           "<div class=\"status-row\">"
           "<div>"
           "<div class=\"status-label\">Pitch</div>"
           "<div class=\"status-value\" id=\"pitch\">-</div>"
           "<div class=\"status-info\" id=\"pitch_scaled\"></div>"
           "</div>"
           "</div>"
           "<div class=\"status-row\">"
           "<div>"
           "<div class=\"status-label\">Ground Angle</div>"
           "<div class=\"status-value\" id=\"ground_angle\">-</div>"
           "<div class=\"status-info\" id=\"ground_angle_scaled\"></div>"
           "</div>"
           "</div>"
           "</div>"
           "</div>"
           
           "<!-- Pressure Data -->"
           "<div class=\"status-card\">"
           "<div class=\"card-header\">"
           "<h2>Cylinder Pressure</h2>"
           "</div>"
           "<div class=\"card-body\">"
           "<div class=\"status-row\">"
           "<div>"
           "<div class=\"status-label\">Bottom Cylinder</div>"
           "<div class=\"status-value\" id=\"bottom_pressure\">-</div>"
           "<div class=\"status-info\" id=\"bottom_pressure_scaled\"></div>"
           "</div>"
           "</div>"
           "<div class=\"status-row\">"
           "<div>"
           "<div class=\"status-label\">Top Cylinder</div>"
           "<div class=\"status-value\" id=\"top_pressure\">-</div>"
           "<div class=\"status-info\" id=\"top_pressure_scaled\"></div>"
           "</div>"
           "</div>"
           "</div>"
           "</div>"
           
           "<!-- Configuration Info -->"
           "<div class=\"status-card\">"
           "<div class=\"card-header\">"
           "<h2>Configuration</h2>"
           "</div>"
           "<div class=\"card-body\">"
           "<div class=\"status-row\">"
           "<div class=\"status-label\">Status:</div>"
           "<div id=\"enabled_status\">-</div>"
           "</div>"
           "<div class=\"status-row\">"
           "<div class=\"status-label\">Byte Offset:</div>"
           "<div id=\"byte_offset\">-</div>"
           "</div>"
           "<div class=\"status-row\">"
           "<div class=\"status-label\">Data Range:</div>"
           "<div id=\"byte_range\">-</div>"
           "</div>"
           "</div>"
           "</div>"
           
           "</div>"
           "<footer style=\"text-align: center; padding: 20px 30px; border-top: 1px solid #dee2e6; color: #666; background-color: #f8f9fa;\">OpENer Ethernet/IP for ESP32-P4 | Adam G Sweeney 11-15-2025</footer>"
           "</div>"
           "</div>"
           "<script>"
           "function updateStatus() {"
           "  fetch('/api/mpu6050/status')"
           "    .then(r => {"
           "      if (!r.ok) {"
           "        throw new Error('HTTP ' + r.status);"
           "      }"
           "      return r.json();"
           "    })"
           "    .then(data => {"
           "      if (data.roll !== undefined) {"
           "        document.getElementById('roll').textContent = data.roll.toFixed(2) + String.fromCharCode(176);"
           "        document.getElementById('roll_scaled').textContent = 'Scaled: ' + data.roll_scaled;"
           "      }"
           "      if (data.pitch !== undefined) {"
           "        document.getElementById('pitch').textContent = data.pitch.toFixed(2) + String.fromCharCode(176);"
           "        document.getElementById('pitch_scaled').textContent = 'Scaled: ' + data.pitch_scaled;"
           "      }"
           "      if (data.ground_angle !== undefined) {"
           "        document.getElementById('ground_angle').textContent = data.ground_angle.toFixed(2) + String.fromCharCode(176);"
           "        document.getElementById('ground_angle_scaled').textContent = 'Scaled: ' + data.ground_angle_scaled;"
           "      }"
           "      if (data.bottom_pressure_psi !== undefined) {"
           "        document.getElementById('bottom_pressure').textContent = data.bottom_pressure_psi.toFixed(2) + ' PSI';"
           "        document.getElementById('bottom_pressure_scaled').textContent = 'Scaled: ' + data.bottom_pressure_scaled;"
           "      }"
           "      if (data.top_pressure_psi !== undefined) {"
           "        document.getElementById('top_pressure').textContent = data.top_pressure_psi.toFixed(2) + ' PSI';"
           "        document.getElementById('top_pressure_scaled').textContent = 'Scaled: ' + data.top_pressure_scaled;"
           "      }"
           "      if (data.enabled !== undefined) {"
           "        document.getElementById('enabled_status').textContent = data.enabled ? 'Enabled' : 'Disabled';"
           "        document.getElementById('enabled_status').style.color = data.enabled ? '#28a745' : '#dc3545';"
           "      }"
           "      if (data.byte_offset !== undefined) {"
           "        document.getElementById('byte_offset').textContent = data.byte_offset;"
           "      }"
           "      if (data.byte_range_start !== undefined && data.byte_range_end !== undefined) {"
           "        document.getElementById('byte_range').textContent = data.byte_range_start + '-' + data.byte_range_end;"
           "      }"
           "    })"
           "    .catch(err => {"
           "      console.error('Status update error:', err);"
           "    });"
           "}"
           "updateStatus();"
           "setInterval(updateStatus, 250);"
           "</script>"
           "</body>"
           "</html>";
}
